# Generated by Django 4.1.4 on 2023-01-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigNomeMateria", models.CharField(max_length=30)),
                ("codigoTurma", models.CharField(max_length=30)),
                ("ano", models.CharField(max_length=30)),
                ("semestre", models.CharField(max_length=30)),
                ("professor", models.CharField(max_length=30)),
                ("cargahoraria", models.CharField(max_length=30)),
                ("horario", models.CharField(max_length=30)),
                ("vagasOfertadas", models.CharField(max_length=30)),
                ("vagasOcupadas", models.CharField(max_length=30)),
                ("local", models.CharField(max_length=30)),
                ("horarioSeparado", models.CharField(max_length=30)),
                ("percDisciplina", models.CharField(max_length=30)),
                ("salaSeparada", models.CharField(max_length=30)),
                ("predio", models.CharField(max_length=30)),
                ("lotacao", models.CharField(max_length=30)),
                ("percOcupacaoReal", models.CharField(max_length=30)),
                ("percOcupacaoTotal", models.CharField(max_length=30)),
            ],
        ),
    ]
