
name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}

    # # Testa a matriz imprimindo a versão atual do Python
    # - name: Display Python version
    #   run: python -c "import sys; print(sys.version)"

    # dependencias python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip freeze > requirements.txt
    
    - name: Run Tests
      run: |
        python TestesUnitarios.py 